# Generated by Django 5.2.6 on 2025-09-25 21:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=5)),
                ('atomic_number', models.IntegerField()),
                ('atomic_mass', models.DecimalField(decimal_places=12, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('category', models.CharField(max_length=10)),
                ('ntm', models.CharField(max_length=10)),
                ('isotopes', models.CharField(max_length=10)),
                ('ionic_compounds', models.CharField(max_length=10)),
                ('Applications', models.CharField(max_length=10)),
                ('History', models.CharField(max_length=10)),
                ('discoverer', models.CharField(max_length=10)),
                ('tod', models.CharField(max_length=10)),
                ('Safety', models.CharField(max_length=30)),
                ('interesting_facts', models.CharField(max_length=70)),
            ],
        ),
    ]
